# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: runid
  value: ""

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: 'x64'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here      
      az extension add -n ml -y
- task: Bash@3
  displayName: 'Az Login'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here      
      az login --service-principal -u $(clientid) -p $(secret) --tenant $(tenantid)
- task: Bash@3
  displayName: 'az version'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      az --version
      # az account show
- task: Bash@3
  displayName: 'configure defaults'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here      
      az extension add -n ml -y --version 2.2.1
      az configure --defaults group=mlopsv2test workspace=bbezmlaml location=eastus2 
- task: Bash@3
  displayName: 'Run Training pipeline'
  continueOnError: true
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here      
      az ml job create -s -f src/workshop/core/pipelines/training_pipeline.yml
- task: Bash@3
  displayName: 'Feature Engineering'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      az ml job create -f src/workshop/core/data_engineering/feature_engineering.yml 
- task: Bash@3
  displayName: 'Training Only'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      az ml job create -f src/workshop/core/training/ml_training.yml  
- task: Bash@3
  displayName: 'Evaluating ...'
  continueOnError: true
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      az ml job create -f src/workshop/core/evaluating/ml_evaluating.yml  
- task: Bash@3
  displayName: 'Endpoint Creation'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      az ml online-endpoint create --file src/workshop/core/scoring/endpoint.yml
- task: Bash@3
  displayName: 'Deployment ...'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      az ml online-deployment create --file src/workshop/core/scoring/deployment.yml  
- task: Bash@3
  displayName: 'Score Testing...'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      az ml online-endpoint invoke -n bbmlopsendpt --deployment green --request-file src/workshop/core/scoring/scoring_test_request.json    